# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'AgoraGameEngine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'AgoraRtcEngine_iOS_Preview', '4.0.0.preview.3'
  pod 'AgoraUIKit-iOS', '~> 1.0.1'
  pod 'AgoraSyncManager', :path => 'AgoraSyncManager'
  pod 'AgoraGame_iOS', '2.0.1'
  pod 'OpenSSL-Universal', '1.0.2.17'
end

